services:
  backend:
    build: .
    container_name: face-backend
    volumes:
      - .:/app
      - ./employees_data:/app/employees_data
      - ./storage:/app/storage
      - ./database:/app/database
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_CONFIG_DIR=/tmp/Ultralytics
      - CAMERA_SOURCE=http://10.0.0.5:4747/videofeed
    stdin_open: true
    tty: true